---
macos:
  config:

  # General UI/UX

    # Expand save panel by default
    - domain: NSGlobalDomain
      key: NSNavPanelExpandedStateForSaveMode
      value: -bool true

    # Save to disk rather than iCloud by default
    - domain: NSGlobalDomain
      key: NSDocumentSaveNewDocumentsToCloud
      value: -bool false

    # Disable smart quotes
    - domain: NSGlobalDomain
      key: NSAutomaticQuoteSubstitutionEnabled
      value: -bool false

    # Disable smart dashes
    - domain: NSGlobalDomain
      key: NSAutomaticDashSubstitutionEnabled
      value: -bool false

    # Save screenshots to desktop
    - domain: com.apple.screencapture
      key: location
      value: -string "${HOME}/Desktop"

    # Save screenshots as .png
    - domain: com.apple.screencapture
      key: type
      value: -string "png"

    # Enable sub-pixel rendering for external displays
    - domain: NSGlobalDomain
      key: AppleFontSmoothing
      value: -int 2

    # Only show scrollbars when scrolling
    - domain: NSGlobalDomain
      key: AppleShowScrollBars
      value: -string WhenScrolling

  # Trackpad 

    # Trackpad - enable two finger secondary click
    - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
      key: TrackpadCornerSecondaryClick
      value: -int 1
    - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
      key: TrackpadRightClick
      value: -bool true
      
  # Security 

    # Require password when awoken from the screensaver
    - domain: com.apple.screensaver
      key: askForPassword
      value: -bool true

    # Require password immediately after screen lock
    # this isn't currently working https://github.com/mathiasbynens/dotfiles/issues/809
    - domain: com.apple.screensaver
      key: askForPasswordDelay
      value: -int 0

  # Mac App Store
  
    # Enable the automatic update check
    - domain: com.apple.SoftwareUpdate
      key: AutomaticCheckEnabled
      value: -bool true
  
    # Check for updates daily
    - domain: com.apple.SoftwareUpdate
      key: ScheduleFrequency
      value: -int 1

    # Download newly available updates in background
    - domain: com.apple.SoftwareUpdate
      key: AutomaticDownload
      value: -int 1

  # Finder

    # Use list view in finder views
    - domain: com.apple.finder
      key: FXPreferredViewStyle
      value: -string "Nlsv"

    # Group by kind in finder views
    - domain: com.apple.Finder
      key: FXPreferredGroupBy
      value: -string "kind"

    # Show external hard drives on desktop
    - domain: com.apple.finder
      key: ShowExternalHardDrivesOnDesktop
      value: -bool true

    # Show network drives on desktop
    - domain: com.apple.finder
      key: ShowMountedServersOnDesktop
      value: -bool true

    # Show removable drives on desktop
    - domain: com.apple.finder
      key: ShowRemovableMediaOnDesktop
      value: -bool true

    # Search the current folder by default in finder
    - domain: com.apple.finder
      key: FXDefaultSearchScope
      value: -string "SCcf"

    # Do not show a warning modal when changing file extension
    - domain: com.apple.finder
      key: FXEnableExtensionChangeWarning
      value: -bool false

    # Delete items from the Trash after 30 days
    - domain: com.apple.finder
      key: FXRemoveOldTrashItems
      value: -bool true

    # Disable the warning when changing a file extension
    - domain: com.apple.finder
      key: FXEnableExtensionChangeWarning
      value: -bool false

    # Automatically open a new Finder window when a volume is mounted
    - domain: com.apple.frameworks.diskimages 
      key: auto-open-ro-root 
      value: -bool true
    - domain: com.apple.frameworks.diskimages 
      key: auto-open-rw-root 
      value: -bool true
    - domain: com.apple.finder 
      key: OpenWindowForNewRemovableDisk 
      value: -bool true

  # Dock

    # Set dock icon size
    - domain: com.apple.dock
      key: tilesize
      value: -int 42

    # Minimize windows into their dock icon
    - domain: com.apple.dock
      key: minimize-to-application
      value: -bool true

    # Show indicator lights in the dock
    - domain: com.apple.dock
      key: show-process-indicators
      value: -bool true

    # Autohide the dock when not in use
    - domain: com.apple.dock
      key: autohide
      value: -bool true

    # Remove the delay when showing the dock
    - domain: com.apple.dock 
      key: autohide-delay 
      value: -float 0 
      
    # Set a fast animation speed for the dock
    - domain: com.apple.dock 
      key: autohide-time-modifier 
      value: -float 0.5
      
  # Safari

    # Prevent Safari from opening ‘safe’ files automatically after downloading
    - domain: com.apple.Safari
      key: AutoOpenSafeDownloads
      value: -bool false

    # Enable “Do Not Track”
    - domain: com.apple.Safari
      key: SendDoNotTrackHTTPHeader
      value: -bool true
  
  # Photos

    # Prevent Photos from opening automatically when devices are plugged in
    - domain: com.apple.ImageCapture
      key: disableHotPlug
      value: -bool true