---
- name: Remove default icons
  shell: "dockutil --remove {{ item }}"
  ignore_errors: true
  with_items: "{{ dock_default_apps }}" 

- name: Add apps to dock
  shell: "dockutil --find {{ item.name }} || dockutil --add {{ item.path }} --replacing {{ item.name }}"
  with_items: "{{ dock_apps }}"

- name: Position apps in dock
  shell: "dockutil --move {{ item.name }} --position {{ item.pos }}"
  with_items: "{{ dock_apps }}"
